name: fwtest

on: 
  workflow_dispatch:
    inputs: 
      environment: 
        required: true
        default: 'Stop'
        description: Please select the FW action
        type: choice
        options:
        - stop
        - start


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    - name: aztests
      shell: pwsh
      run: |
          $rgname = "WinImageBuilderRG"
          $fwname = "fwtest"
          az network firewall show -n $fwname --resource-group $rgname | ConvertFrom-Json
          # $azfw = Get-AzFirewall -Name $fwname -ResourceGroupName $rgname
          if ("${{ github.event.inputs.environment }}" -eq 'Stop') {
          write-host "Stop was selected"
                        } 
          
          if ("${{ github.event.inputs.environment }}" -eq 'Start') {
          write-host "Start was selected"
          az group list
                        } 
    
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $rgname = "WinImageBuilderRG"
          $fwname = "fwtest"
          $azfw = Get-AzFirewall -Name $fwname -ResourceGroupName $rgname
          if ("${{ github.event.inputs.environment }}" -eq 'Stop') {
          write-host "Stop was selected"
          $fwstat = (Get-AzFirewall -ResourceGroupName $rgname -Name $fwname).IpConfigurations
            If ($fwstat -ne "$null") {
                Write-Host "##[debug]Stopping Azure FireWall, it might take few minutes, please wait...."
                [System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId((Get-Date), 'Israel Standard Time')
                $azfw.Deallocate()
                Set-AzFirewall -AzureFirewall $azfw
                $fwstat = (Get-AzFirewall -ResourceGroupName $rgname -Name $fwname).IpConfigurations
                If ($null -eq $fwstat) {Write-Host "##vso[task.logissue type=warning;]Firewall is in a stopped state"}
                [System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId((Get-Date), 'Israel Standard Time')
                      }
            Else {Write-Host "##vso[task.logissue type=warning;]Firewall is already in a stopped state"}
                        } 
          
          if ("${{ github.event.inputs.environment }}" -eq 'Start') {
              $fwstat = (Get-AzFirewall -ResourceGroupName $rgname -Name $fwname).IpConfigurations
              If ("$null" -eq $fwstat) {
                  Write-Host "##[debug]Starting Azure FireWall, it might take few minutes, please wait...."
                  [System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId((Get-Date), 'Israel Standard Time')
                  $vnet = Get-AzVirtualNetwork -ResourceGroupName $rgname -Name "we-hub-vnet"
                  $publicip1 = Get-AzPublicIpAddress -Name "we-hub-fw-pip" -ResourceGroupName $rgname
                  $azfw.Allocate($vnet,@($publicip1))
                  Set-AzFirewall -AzureFirewall $azfw
                  $fwstat = (Get-AzFirewall -ResourceGroupName $rgname -Name $fwname).IpConfigurations
                  If ($null -ne $fwstat) {Write-Host "##vso[task.logissue type=warning;]Firewall is in a started state"}
                  [System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId((Get-Date), 'Israel Standard Time')
                        }
              Else {Write-Host "##vso[task.logissue type=warning;]Firewall is already in a started state"}
                        }  
          write-host "Start was selected"
          az group list
                        } 
        azPSVersion: "latest"

          
